### ISSUE TITLE
Endpoint de mesa retornando apenas informações de mesa

### ISSUE THREAD

**Issue by lucasdemoraesc** [DLL-S/comcer-backend#27]

**Comment by lucasdemoraesc** [comment]
@leonardopereira10 não encontrei esse endpoint

**Comment by leonardopereira10** [comment]
Alteração realizada na issue 22, não foi disponibilizado endpoint especifico, apenas removendo informações que fogem ao contexto da listagem

"retornar apenas mesa #22"
